# Generated by Django 2.1.5 on 2019-01-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_article_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1024, unique=True),
        ),
    ]
