# Generated by Django 2.1.5 on 2019-01-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20190131_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='requested_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
